# Thymeleaf
thymeleaf:
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  cache: false

# Spring MVC
mvc:
  static-path-pattern: /static/**

# Data Source Configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mystudy
    username: subuser
    password: mypassword
    driverClassName: org.mariadb.jdbc.Driver

# Encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 80

  mvc:
    converters:
      preferred-json-mapper: gson

# Servlet Configuration
servlet:
  multipart:
    max-file-size: 1MB
    max-request-size: 10MB

# JPA Configuration
jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  properties:
    hibernate.format_sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  
# Custom Configuration (if required)
noticefile:
  path: C:\wark\sts-4.18.0.RELEASE-workspace\TwoProject\src\main\resources\static\resources\user\file