name: Java CI with Gradle
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew # Make the Gradle Wrapper executable
      - name: Build with Gradle
        run: ./gradlew build # Run the Gradle build

      # Set environment variables for the application
      - name: Set up MariaDB for application
        run: |
          echo "spring.datasource.url=jdbc:mariadb://localhost:3306/mystudy" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.username=subuser" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.password=mypassword" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.driver-class-name=org.mariadb.jdbc.Driver" >> $GITHUB_WORKSPACE/application.properties

      # Now you can run your application using Gradle
      - name: Run Application
        run: ./gradlew bootRun
