name: Java CI with Gradle
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Add permission
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      # Set environment variables for the application
      - name: Set up MariaDB for application
        env:
          SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/mystudy
          SPRING_DATASOURCE_USERNAME: subuser
          SPRING_DATASOURCE_PASSWORD: mypassword
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver

      # Now you can run your application using Gradle
      - name: Run Application
        run: |
          echo "spring.datasource.url=${SPRING_DATASOURCE_URL}" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.username=${SPRING_DATASOURCE_USERNAME}" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}" >> $GITHUB_WORKSPACE/application.properties
          echo "spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}" >> $GITHUB_WORKSPACE/application.properties
          ./gradlew bootRun
